In [2]:
import pandas as pd

In [4]:
import pandas as pd

df = pd.read_csv("../data/Global_Superstore.csv", encoding="latin1")

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [7]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [8]:
df["Postal Code"] = df["Postal Code"].fillna(df["Postal Code"].median())

In [9]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
City              0
State             0
Country           0
Postal Code       0
Market            0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Cost     0
Order Priority    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [13]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

C:\Users\aqeel\AppData\Local\Temp\ipykernel_21616\2772104420.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order Date"] = pd.to_datetime(df["Order Date"])
C:\Users\aqeel\AppData\Local\Temp\ipykernel_21616\2772104420.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [14]:
df.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
City                         str
State                        str
Country                      str
Postal Code              float64
Market                       str
Region                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority               str
dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  datetime64[us]
 3   Ship Date       51290 non-null  datetime64[us]
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     51290 non-null  float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 9.4 MB

In [16]:
df.to_csv("../cleaned_data/Global_Superstore_Cleaned.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\cleaned_data'

In [17]:
import os
print(os.getcwd())

c:\Users\aqeel\Documents\SkillCraft\SkillCraft_Task2_DataCleaning\notebook

In [18]:
print(os.listdir())

['Data_Cleaning.ipynb']

In [19]:
import os
print(os.getcwd())

c:\Users\aqeel\Documents\SkillCraft\SkillCraft_Task2_DataCleaning\notebook

In [21]:
import os

print("Current Folder:", os.getcwd())
print("Parent Folder Contents:", os.listdir(".."))

Current Folder: c:\Users\aqeel\Documents\SkillCraft\SkillCraft_Task2_DataCleaning\notebook
Parent Folder Contents: ['cleaned data', 'data', 'notebook', 'README.md', 'requirements.txt']

In [22]:
print(os.listdir(".."))

['cleaned data', 'data', 'notebook', 'README.md', 'requirements.txt']

In [23]:
df.to_csv("../cleaned_data/Global_Superstore_Cleaned.csv", index=False)
print("Data Cleaning Completed Successfully!")

Data Cleaning Completed Successfully!

In [2]:
df.head()

NameError: name 'df' is not defined

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/Global_Superstore.csv", encoding="latin1")

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical